Permisions/auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

Permisions/home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [

    path('',views.index ,name="index"),
    path('signup/',views.sign_up ,name="signup"),
    path('login/',views.Log_in ,name="login"),
    path('dashboard/',views.dashboard ,name="dashboard"),
    path('logout/',views.log_out ,name="logout"),

]

Permisions/home/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title=models.CharField(max_length=100)
    desc=models.CharField(max_length=300)

Permisions/home/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User


class SignUp(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']


class EditUserPrifoleForm(UserChangeForm):
    
    password=None
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','is_staff']
        labels={'email':'Email'}

class AdminUserPrifoleForm(UserChangeForm):
    
    password=None
    class Meta:
        model=User
        fields='__all__'
        labels={'email':'Email'}

Permisions/home/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       SetPasswordForm, UserChangeForm,
                                       UserCreationForm)
from django.contrib.auth.models import Group, User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from .forms import AdminUserPrifoleForm, EditUserPrifoleForm, SignUp

# Create your views here.


def index(request):

    if request.method == 'POST':
        pass
    else:
        pass
    data = {}
    return render(request, "index.html", data)

def sign_up(request):
    if request.method == 'POST':
        form = SignUp(request.POST)
        if form.is_valid():
            messages.success(request, "Your account created succesfuly !!")
            # form.save() # save user only
            user = form.save()
            group = Group.objects.get(name='viewer') # adding user in to a group on Signup
            user.groups.add(group)
            form = SignUp()
    else:
        form = SignUp()
    data = {'form': form}
    return render(request, "signup.html", data)

def Log_in(request):
    mydata = {}
    if not request.user.is_authenticated:
        if request.method == 'POST':
            login_form = AuthenticationForm(request=request, data=request.POST)
            if login_form.is_valid():
                uname = login_form.cleaned_data['username']
                upass = login_form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, "You are successfuly login")
                    return HttpResponseRedirect("/dashboard/")
        else:
            login_form = AuthenticationForm()
        mydata = {'form': login_form}
        return render(request, "signin.html", mydata)
    else:
        return redirect("dashboard")


def dashboard(request):
    if request.user.is_authenticated:
        name = request.user
        data = {'name': name}
        return render(request, "dashboard.html", data)
    else:
        return redirect("login")


def log_out(request):

    logout(request)
    return redirect("login")

Permisions/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Authentication {% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
    <style>
      .success {
        color: green;
      }
      .error {
        color: red;
      }
    </style>
  </head>
  <body>




    
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">My Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/dashboard/">dashboard</a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/signup/">Signup</a>
          </li>
          {% endif %}
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


  {% block content %}
        
  {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </body>
    
</html>

Permisions/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock title %}
{% load crispy_forms_tags %}
{% block content %}



<div class="row m-5 border rounded">

  <h1 class="m-5">This is Dashboard Page</h1>
  {% if messages %} {% for message in messages %}
  <small {% if message.tags %} class="{{message.tags}}" {% endif %}>
    {{message}}
  </small> <br>{% endfor%}
  {%endif%}


  <div class="col-6 border rounded p-4 m-4 ">

    <h2>Welcome {{name}}</h2>
    {% if perms.home.add_blog %}
    <input class="btn btn-info" href="/home/" type="button" value="Add">
    {% else %}
    <h3>No add permision</h3>
    {% endif%}

    {% if perms.home.change_blog %}
    <input class="btn btn-warning" class="btn btn " type="button" value="Edit">
    {% else %}
    <h3>No edit permision</h3>
    {% endif%}


    {% if perms.home.delete_blog %}
    <input class="btn  btn-danger " type="button" value="Delete">
    {% else %}
    <h3>No delete permision</h3>
    {% endif%}

    {% if perms.home.view_blog %}
    <input class="btn btn-success" type="button" value="View">
    {% else %}
    <h3>No view permision</h3>
    {% endif%}


  {% endblock content %}

Permisions/templates/index.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock title %}
{% load crispy_forms_tags %}


{% block content %}


{% endblock content %}

Permisions/templates/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">

        <div class="row">
          <div class="col-5 border rounded p-4 m-4 ">
            <form action="#" method="POST" id="officeform" novalidate>
              {%csrf_token%}
              {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
              <p>{{error}}</p>
              {% endfor %}
              {% endif %}          
              <h1 style="margin-left: 5%">login</h1>
              {{form|crispy}}
              <input class='btn btn-info' type="submit" value="Login" />
            </form>
          </div>
    {% endblock content %}

Permisions/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="container">
    
        <div class="row">
          <div class="col-5 border rounded p-4 m-4 ">
            <form action="" method="POST" id="officeform" novalidate>
              {%csrf_token%}

              {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
              <p>{{error}}</p>
              {% endfor %}
              {% endif %}
            
              <h1 style="margin-left: 5%">Signup</h1>
              {% for fm in form  %}

              {{fm.label_tag}} <br> {{fm}} {{fm.error|striptags}} <br> <br>
                
              {% endfor %}
              <input class='btn btn-info' type="submit" value="SignUp" />
            </form>
          </div>
    {% if messages %} {% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>
      {{message}}
    </small>
    {% endfor %} {% endif %}

    <a href="/login/"><h3>Sign_in</h3></a>
    
    {% endblock content %}